### ISSUE TITLE
IX Updated UI

### ISSUE THREAD

**Issue by konzz** [huridocs/uwazidocs#5830]
```[tasklist]
### Tasks for PDF sidepanel
- [x] Date fields
- [x] Numeric fields
- [x] Clear selection button, Click to fill buttons, functionality to remove/create/update selections
- [x] Request entities on route loader, check that only needed fields are requested @grafitto
- [x] Redesign the button to accept a single suggestions
- [x] Solve visual problems on the sidepanel pdf rendering
- [x] When the PDF opens the view should scroll to the selection, if any exist.
- [x] Implement form for sidepanel to update files and selections. Disable save button if no changes and during save. Validate entity field.
```

**Comment by juanmnl** [comment]
We have 2 tables for IX, the first is a straight forward table component.

**Extractors list**

<img width="1440" alt="Screenshot 2023-05-18 at 18 28 49" src="https://github.com/huridocs/uwazi/assets/699945/3d93cf26-d150-4faf-a068-1537a6a8852d">

*The "add extractor" modal will remain the same, for now, as we still need to think of a better flow that matches the new UI and scales for newer properties that we'll add.

**Property IX** 
This one introduces a lot of complex behaviors. You may find some of the actions redundant but once they evolve, they'll branch out with specific behaviors. (trust me 😅)

- Our first "rich table heading" which includes: property symbol, the property string and the templates it's being used for + the drawer trigger "Stats & filters"
- Each cell will have a max of 2 lines of text
- A Tooltip appears on hover, on cells that have text overflowing, displaying its full content
- The toggle is still being discussed as something we may not need, but the status indicator will remain for sure
- We'll use, for now, the same component we have for opening the pdf (feel free, as for the "add extractor", to chose if adding the wrapper and buttons of the new UI)
- For pagination, it was requested that we show 100 items per page

<img width="1191" alt="Screenshot 2023-05-18 at 18 42 13" src="https://github.com/huridocs/uwazi/assets/699945/24411cbc-247d-4bb3-9703-193eca5abee6">

**Tooltip on hover**
<img width="665" alt="Screenshot 2023-05-18 at 18 46 31" src="https://github.com/huridocs/uwazi/assets/699945/75f41bb8-f23a-4371-9daf-af3d156e8bbe">

**Open pdf**
<img width="1440" alt="Screenshot 2023-05-18 at 18 47 28" src="https://github.com/huridocs/uwazi/assets/699945/1b79f543-eb1b-4535-8da4-cea1d5274562">

**Stats & Filters** (behavior needs a bit more of exploration and clarification)
<img width="387" alt="Screenshot 2023-05-18 at 18 47 57" src="https://github.com/huridocs/uwazi/assets/699945/9d0c7db9-e701-42af-a18c-327d98dcff6f">

**Find suggestion** (the log lives now outside of the button)
<img width="755" alt="Screenshot 2023-05-18 at 18 50 06" src="https://github.com/huridocs/uwazi/assets/699945/e02337d3-7b90-4262-bc5c-2f898a7c22b4">

**Select and multi-select**
Here's where you could find a bit of redundant behavior between the header checkbox and the "select all from page" in the action bar. Both are important and will add elasticity as it evolves.

<img width="1191" alt="Screenshot 2023-05-18 at 18 51 12" src="https://github.com/huridocs/uwazi/assets/699945/17635e9e-78e5-4466-8130-d763ffd855fc">

<img width="1191" alt="Screenshot 2023-05-18 at 18 53 21" src="https://github.com/huridocs/uwazi/assets/699945/f696e080-19c8-4c6f-afa0-f86aac79627e">

***Backend Specifics***
- Suggestions endpoint should also return the total amount of suggestions (For the footer of the table to show "Showing x of x suggestions"
- Separate suggestions and aggregations endpoints.
- All filters work as an OR
- Filters only apply to their category E.g. if you select "Match" you will only see suggestions that match and have labeled data.



[Prototype](https://www.figma.com/proto/HZX8qH0Aw8WiSch3Axczrn/new-comps?page-id=9%3A2&type=design&node-id=838-17069&viewport=-1298%2C629%2C0.22&scaling=min-zoom&starting-point-node-id=838%3A18258)

**Comment by RafaPolit** [comment]
- Please, add a "white space no-wrap" property to the labels in "Title for", as they are wrapping up when you get long template names.
- The yellow X on the PDF viewer should be considered a "Nice to Have" since we have the "Clear Selection" on there.

**Comment by konzz** [comment]
Check #5477

**Comment by txau** [comment]
Check  #5954

**Comment by Zasa-san** [comment]
I think it would be really helpful if we list all actions users need to make on these screens, kinda like users stories, to avoid forgetting a flow that might not be immediately obvious.

**Comment by juanmnl** [comment]
**Update** Changed the label from "Completion" to "Pending" and removed the helper box as we don't have any text.

![Image](https://github.com/huridocs/uwazi/assets/699945/2cb4c9cf-c6a3-49a9-9ebb-3e0463b2eb9e)

**Comment by konzz** [comment]
About confirmation modals when accepting suggestions, yes they are gone and the behavior is accepting only for one language.

**Comment by Zasa-san** [comment]
Review the problem described in #5512

**Comment by juanmnl** [comment]
**Update** for the accept button as a pattern for actions inside complex components (like rows in a table)

The button comes from the pill/tag element we already use, but with an added "shadow-sm" to signal available interaction, and some states.
<img width="1410" alt="Screenshot 2023-08-14 at 22 46 44" src="https://github.com/huridocs/uwazi/assets/699945/2ab0e9d7-cb3a-4bc2-b926-06922d06326e">

IX table with new inner actions.
![main-2](https://github.com/huridocs/uwazi/assets/699945/2d3bb4ff-0694-40c4-8178-8bc280a9f9e7)

Tooltip on hover for disabled actions.
![main-1](https://github.com/huridocs/uwazi/assets/699945/6d390bc6-e354-44b0-8ffb-c69c6bc07497)

Accepted items become a reduced version of itself, so they can get out of the way.
![main](https://github.com/huridocs/uwazi/assets/699945/9637fc92-7f0a-4337-93cb-bb069365159e)

**Comment by juanmnl** [comment]
### References

**Drawer layout** (#6085)
<img width="566" alt="Screenshot 2023-08-18 at 10 42 08" src="https://github.com/huridocs/uwazi/assets/699945/60bd6264-e7d7-4961-b56e-3786c3f9d2f4">

**Notification: Alert - warning**
<img width="1023" alt="Screenshot 2023-08-18 at 10 42 23" src="https://github.com/huridocs/uwazi/assets/699945/f607e12f-83e7-4d55-8d66-c24be7791193">

**Comment by Zasa-san** [comment]
![image](https://github.com/huridocs/uwazi/assets/71732018/42b2f38a-3885-4765-85ba-5ddbc94c1870)

This notification in the sidepanel is going to be a standalone implementation since our current popup notifications do not adjust to this one. We might want to review all of our notification types in https://github.com/huridocs/uwazi/issues/6085

@juanmnl @konzz
