### ISSUE TITLE
UI improvements

### ISSUE THREAD

**Issue by juanmnl** [huridocs/uwazidocs#6085]
- [x] [table checkbox: bounding box squared shape](https://github.com/huridocs/uwazi/issues/6085#issuecomment-1681434176)
- [x] [breadcrumb container: box height (line-height)](https://github.com/huridocs/uwazi/issues/6085#issuecomment-1681435944)
- [x] [tab navigation: font-size, weight and inactive text color](https://github.com/huridocs/uwazi/issues/6085#issuecomment-1681438428)
- [x] [*drawer layout: fixed action bar (should be the same layout as the main section's layout)](https://github.com/huridocs/uwazi/issues/6085#issuecomment-1681445157)
- [x] [settings > users & groups: drawer: groups card: font-size, vertical alignment & dropdown position and width on interaction.](https://github.com/huridocs/uwazi/issues/6085#issuecomment-1681450400)
- [x] [main section: padding against the sideNav (16px)](https://github.com/huridocs/uwazi/issues/6085#issuecomment-1681452372)
- [ ] [table: table-header(s) & main data cells: color](https://github.com/huridocs/uwazi/issues/6085#issuecomment-1681454121)
- [x] [Overlay resizing glitch when opening the drawer](https://github.com/huridocs/uwazi/issues/6085#issuecomment-1682341999)
- [x] [switch red to pink as danger color](https://github.com/huridocs/uwazi/issues/6085#issuecomment-1682371395)

We need to discuss about font-weights in general :D

(see references for each task in the comments)

**Comment by juanmnl** [comment]
### **table checkbox: bounding box squared shape**

**Current:**
<img width="796" alt="Screenshot 2023-07-31 at 14 04 48" src="https://github.com/huridocs/uwazi/assets/699945/01e3694a-ce36-4b9b-aa6c-d9bae5029c34">

**Reference:**
<img width="665" alt="Screenshot 2023-07-31 at 14 07 47" src="https://github.com/huridocs/uwazi/assets/699945/e5b9bc17-d266-4221-a296-e60052a5eeb4">

**Comment by juanmnl** [comment]
### **breadcrumb container: box height (line-height)**

**Current:**
<img width="934" alt="Screenshot 2023-07-31 at 14 06 25" src="https://github.com/huridocs/uwazi/assets/699945/c0d3e074-4372-46c8-be94-c9b53658c44e">

**Reference:**
<img width="1430" alt="Screenshot 2023-07-31 at 14 06 20" src="https://github.com/huridocs/uwazi/assets/699945/26861689-f9ad-425f-abc0-c4fa2787d89b">

**Comment by juanmnl** [comment]
### **tab navigation: font-size, weight and inactive text color**

**Current:**
<img width="1079" alt="Screenshot 2023-08-16 at 19 34 31" src="https://github.com/huridocs/uwazi/assets/699945/b651d036-3ca3-4e35-8d1f-6cb791265d21">

**Reference: (*not font-family)**
<img width="1025" alt="Screenshot 2023-07-31 at 14 13 12" src="https://github.com/huridocs/uwazi/assets/699945/7ef1766b-c6d2-4198-a7a6-1747a1444d72">
<img width="1012" alt="Screenshot 2023-07-31 at 14 13 36" src="https://github.com/huridocs/uwazi/assets/699945/f36970c4-fdf8-4a2d-93d1-a411a54895c7">

**Comment by juanmnl** [comment]
### ***drawer layout: fixed action bar - always visible (should be the same layout as the main section's layout)**

**Current:**
<img width="1440" alt="Screenshot 2023-07-31 at 14 15 49" src="https://github.com/huridocs/uwazi/assets/699945/4b6a275a-dfa6-4414-9898-506067c1c7bf">

**Reference:**
<img width="492" alt="Screenshot 2023-08-16 at 19 45 42" src="https://github.com/huridocs/uwazi/assets/699945/8abb5cbf-6c5b-43f4-8873-8b33cd1b3c5e">

**Comment by juanmnl** [comment]
### **settings > users & groups: drawer: groups card: font-size, vertical alignment & dropdown position and width on interaction.**

**Current:**
Font-size:
<img width="680" alt="Screenshot 2023-07-31 at 14 39 48" src="https://github.com/huridocs/uwazi/assets/699945/24257297-618f-4a0e-9e9d-b9d96ae441ae">
Vertical alignment - title - button
<img width="557" alt="Screenshot 2023-07-31 at 14 40 10" src="https://github.com/huridocs/uwazi/assets/699945/331893eb-e9d1-4935-9ee6-ced03fe8600a">
<img width="529" alt="Screenshot 2023-07-31 at 14 40 41" src="https://github.com/huridocs/uwazi/assets/699945/07ba1f4e-6dbf-4718-a9a4-a74b3ef58162">
<img width="537" alt="Screenshot 2023-07-31 at 14 44 05" src="https://github.com/huridocs/uwazi/assets/699945/072a16c2-baa5-4d16-92bd-095fe1ea69a9">

**Reference:**
<img width="707" alt="Screenshot 2023-08-16 at 19 50 57" src="https://github.com/huridocs/uwazi/assets/699945/907af53e-bb64-4b81-96b2-e5401d4ad017">

**Comment by juanmnl** [comment]
### **main section: padding (16px)**

**Current:**
<img width="445" alt="Screenshot 2023-07-31 at 14 36 37" src="https://github.com/huridocs/uwazi/assets/699945/609579d7-9de5-4ab3-b2b7-2477c9b68b52">

**Reference:**
<img width="714" alt="Screenshot 2023-07-31 at 14 37 15" src="https://github.com/huridocs/uwazi/assets/699945/eb0312eb-0564-451f-a7ed-01a4319f62f8">

**Comment by juanmnl** [comment]
### **table: table-header(s) & main data cells: color**

**Current:**
<img width="881" alt="Screenshot 2023-08-16 at 19 42 03" src="https://github.com/huridocs/uwazi/assets/699945/310d25dc-8170-4cad-b1bd-549f7721bba4">

**Reference:**
<img width="833" alt="Screenshot 2023-08-16 at 19 41 32" src="https://github.com/huridocs/uwazi/assets/699945/d2ecb19a-6701-463b-a969-31bea2c00198">

**Comment by juanmnl** [comment]
### **Overlay glitch when opening and closing the drawer**

1. Overlay resize on open and close
2. Drawer flashes in the center of the screen on close.

https://github.com/huridocs/uwazi/assets/699945/70665098-a7d9-4eef-8bb5-79fdb4ffb9a9

**Comment by juanmnl** [comment]
### **Switch all reds to pink as "danger" color**

Same values. **red-600 = pink-600**

<img width="451" alt="Screenshot 2023-08-17 at 09 17 04" src="https://github.com/huridocs/uwazi/assets/699945/0450454e-67c1-4c3f-aaf8-e816b6753188">
