### ISSUE TITLE
Tech debt | Available languages on the system.

### ISSUE THREAD

**Issue by Joao-vi** [huridocs/uwazidocs#7514]
### Problem
Uwazi system needs to work with different languages code and is to clear on code that "language" method, exported by languagesList.ts file, is used to map one language code to another one.

This is how which language code is used: 
1. Files => ISO639_3
2. Entity => ISO639_1
3. OCR => ISO639_1

### Todo

- [x] Create a mapper class to be responsible for translate one language to another.
- [x] Remove 'franc' (franc is ISO639_3 code and also, "franc"  is not a language code).
- [x] Try to remove ElasticLegacyObject.
- [ ] Remove key from available languages (as key stands for ISO639_1)

**Comment by Joao-vi** [comment]
I believe replacing 'key' for 'ISO639_1' is not going be doable because this will require to change in a lot of files, check image bellow. 

<img width="340" alt="image" src="https://github.com/user-attachments/assets/430520a9-9da8-472b-a351-c4194717e9e7">
